// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyWebAppAPI.Models;

[Table("Branch")]
[Index("IsDeleted", Name = "branchIsDeletedIndex")]
public partial class Branch
{
    [Key]
    public int BranchId { get; set; }

    [Required]
    [StringLength(300)]
    public string BranchName { get; set; }

    [Required]
    [StringLength(300)]
    public string SupervisorName { get; set; }

    [Required]
    [StringLength(100)]
    public string SupervisorPhoneNumber { get; set; }

    [StringLength(50)]
    public string SupervisorLandlineNumber { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    // Navigation Properties

    [InverseProperty("Branch")]
    public virtual ICollection<Trainee> Trainees { get; set; } = new List<Trainee>();

    [InverseProperty("Branch")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}