// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyWebAppAPI.Models;

[Table("Course")]
[Index("IsDeleted", Name = "courseIsDeletedIndex")]
public partial class Course
{
    [Key]
    public int CourseId { get; set; }

    [Required]
    [StringLength(100)]
    public string CourseName { get; set; }

    [StringLength(350)]
    public string CourseDescription { get; set; }

    public int CourseDurationInHours { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal CourseCost { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    // Navigation Properties

    [InverseProperty("Course")]
    public virtual ICollection<Subject> Subjects { get; set; } = new List<Subject>();

    [InverseProperty("Course")]
    public virtual ICollection<TraineeCourseRelation> TraineeCourseRelations { get; set; } = new List<TraineeCourseRelation>();

    [InverseProperty("Course")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}