// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyWebAppAPI.Models;

[Table("Subject")]
[Index("IsDeleted", Name = "subjectIsDeletedIndex")]
public partial class Subject
{
    [Key]
    public long SubjectId { get; set; }

    [Required]
    [StringLength(300)]
    public string SubjectName { get; set; }

    public int CourseId { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    // Navigation Properties

    [ForeignKey("CourseId")]
    [InverseProperty("Subjects")]
    public virtual Course Course { get; set; }
}