// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.Eventing.Reader;
using Microsoft.EntityFrameworkCore;

namespace AcademyWebAppAPI.Models;

[Table("Trainee")]
[Index("IsDeleted", Name = "traineeIsDeletedIndex")]
public partial class Trainee
{
    [Key]
    public long TraineeId { get; set; }

    [Required]
    [StringLength(50)]
    public string TraineeNationalId { get; set; }

    [Required]
    [StringLength(300)]
    public string ArabicFullName { get; set; }

    [StringLength(300)]
    public string EnglishFullName { get; set; }

    [Required]
    [StringLength(20)]
    public string Religion { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    [Required]
    [StringLength(20)]
    public string Gender { get; set; }

    [Column(TypeName = "date")]
    public DateTime? BirthDate { get; set; }

    [Required]
    [StringLength(100)]
    public string FirstPhoneNumber { get; set; }

    [StringLength(100)]
    public string SecondPhoneNumber { get; set; }

    [StringLength(50)]
    public string LandlineNumber { get; set; }

    [StringLength(100)]
    public string Recommender { get; set; }

    [Required]
    [StringLength(300)]
    public string AcademicQualification { get; set; }

    public int QualificationObtainingYear { get; set; }

    public int? AcademicYear { get; set; }

    [Required]
    [StringLength(50)]
    public string MilitaryStatus { get; set; }

    [StringLength(100)]
    public string PersonalPhoto { get; set; }

    [StringLength(100)]
    public string NationalIdCardCopy { get; set; }

    [Required]
    [StringLength(100)]
    public string AcademicQualificationCopy { get; set; }

    public int BranchId { get; set; }

    [DefaultValue(true)]
    public bool IsActive { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    // Navigation Properties

    [ForeignKey("BranchId")]
    [InverseProperty("Trainees")]
    public virtual Branch Branch { get; set; }

    [InverseProperty("Trainee")]
    public virtual ICollection<TraineeCourseRelation> TraineeCourseRelations { get; set; } = new List<TraineeCourseRelation>();

    [InverseProperty("Trainee")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}