// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AcademyWebAppAPI.Models;

[Table("Transaction")]
[Index("IsDeleted", Name = "transactionIsDeletedIndex")]
public partial class Transaction
{
    [Key]
    public long TransactionId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TransactionDateTime { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal ReceivedMoneyAmount { get; set; }

    [Required]
    [StringLength(300)]
    public string DashboardUser { get; set; }

    [StringLength(350)]
    public string Notes { get; set; }

    [Required]
    [StringLength(50)]
    public long TraineeId { get; set; }

    public int CourseId { get; set; }

    [DefaultValue(false)]
    public bool IsDeleted { get; set; }

    // Navigation Properties

    [ForeignKey("CourseId")]
    [InverseProperty("Transactions")]
    public virtual Course Course { get; set; }

    [ForeignKey("TraineeId")]
    [InverseProperty("Transactions")]
    public virtual Trainee Trainee { get; set; }
}